! Spectra computed in Electrostatic Hybrid-PIC runs (1D)
!            CALL spectrum(vx,vy,vz,ext,1,1)
!            CALL specpara(vx,vy,vz,ext,1,1)
!            CALL specperp(vx,vy,vz,ext,1,1)
            CALL spectrum(ax,ay,az,ext,0,0)
            CALL specpara(ax,ay,az,ext,0,0)
            CALL specperp(ax,ay,az,ext,0,0)
            
            CALL picpart%GetDensity(R1)
            CALL fftp3d_real_to_complex(planrc,R1,C1,MPI_COMM_WORLD)
            CALL specscpa(C1,ext,0)
!            CALL spectrsc(th,ext,0)
!            CALL specscpa(th,ext,0)
!            CALL specscpe(th,ext,0)
