! Spectra computed in MPROTH runs (HD rotation with 2 or 3 passive scalar)

            CALL spectrum(vx,vy,vz,ext,1,1)
            CALL specpara(vx,vy,vz,ext,1,1)
            CALL specperp(vx,vy,vz,ext,1,1)
            CALL spectrsc(th1,ext)
            CALL specscpa(th1,ext)
            CALL specscpe(th1,ext)
            CALL spectrsc(th2,ext)
            CALL specscpa(th2,ext)
            CALL specscpe(th2,ext)
!!          CALL spectrsc(th3,ext)
!!          CALL specscpa(th3,ext)
!!          CALL specscpe(th3,ext)

!           CALL difucx(vx,th,ext)
!           CALL difucz(vz,th,ext)
!           CALL spec2D(vx,vy,vz,ext,odir,1,1)
!           CALL specsc2D(th,ext,odir)
