! Spectra computed in PROTH runs (HD rotation with passive scalar)

            CALL spectrum(vx,vy,vz,ext,1,1)
            CALL specpara(vx,vy,vz,ext,1,1)
            CALL specperp(vx,vy,vz,ext,1,1)
            CALL spectrsc(th,ext)
            CALL specscpa(th,ext)
            CALL specscpe(th,ext)
!           CALL difucx(vx,th,ext)
!           CALL difucz(vz,th,ext)
!           CALL spec2D(vx,vy,vz,ext,odir,1,1)
!           CALL specsc2D(th,ext,odir)
